import React, { useState } from 'react';
import { Download, FileText, Copy, Check, FileCode, Sparkles, X, ExternalLink } from 'lucide-react';
import { AudioMetrics, NoiseBaselineProfile, AiNoiseDetectionResult } from '../types';

interface ReportExporterProps {
  metrics: AudioMetrics;
  profile: NoiseBaselineProfile;
  latestAiResult: AiNoiseDetectionResult | null;
  isOpen: boolean;
  onClose: () => void;
}

export const ReportExporter: React.FC<ReportExporterProps> = ({
  metrics,
  profile,
  latestAiResult,
  isOpen,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);
  const [geminiState, setGeminiState] = useState<'idle' | 'copied'>('idle');

  if (!isOpen) return null;

  const timestamp = new Date().toLocaleString();

  // Build markdown report content
  const buildReportMarkdown = () => {
    return `
# PROFESSIONAL ACOUSTIC SOUND AUDIT REPORT
**Generated:** ${timestamp}
**Application:** Professional Audio Analysis Suite

---

## 1. SPECTRAL & AUDIO TELEMETRY METRICS
- **Peak Prominent Frequency:** ${metrics.peakFrequencyFormatted || `${metrics.peakFrequencyHz} Hz`} (${metrics.peakNoteName})
- **Peak Prominence Level:** ${metrics.prominenceDb || metrics.peakDb} dBFS
- **Spectral Centroid (Brightness Center):** ${metrics.spectralCentroidHz || 'N/A'} Hz
- **RMS Volume Level:** ${metrics.rmsDb} dBFS
- **Instantaneous Peak Level:** ${metrics.peakDb} dBFS
- **Crest Factor (Dynamic Peak-to-Average):** +${metrics.crestFactorDb} dB
- **Sub-Bass Energy (20-60 Hz):** ${metrics.subBass} %
- **Bass Energy (60-250 Hz):** ${metrics.bass} %
- **Midrange Energy (250-2 kHz):** ${metrics.mid} %
- **Treble Energy (2k-20 kHz):** ${metrics.treble} %
- **Analyzer Frame Rate:** ${metrics.fps} FPS

---

## 2. LONG-TERM BACKGROUND NOISE BASELINE & TRANSIENT AUDIT
- **Calibrated Baseline Status:** ${profile.isCalibrated ? `Calibrated (${profile.lastCalibratedTime || 'Active'})` : 'Uncalibrated (Real-Time Ambient Estimate)'}
- **Measured Ambient Noise Floor:** ${profile.noiseFloorDb} dBFS
- **Signal-to-Noise Ratio (SNR):** +${profile.snrDb} dB
- **Room Acoustic Noise Criteria (NC):** ${profile.noiseCriteriaRating}
- **Dominant Ambient Noise Band:** ${profile.dominantNoiseBand}
- **Impulsive Transient Spikes Detected:** ${profile.transientCount} ${profile.transientsPerMin ? `(Rate: ${profile.transientsPerMin} events/min)` : ''}
- **Transient Acoustic Nature:** Sudden impulsive attacks (e.g. claps, taps, clicks, mic pops with $\\ge 12\\text{ dB}$ rapid energy onset or $\\ge 16\\text{ dB}$ crest factor)

---

## 3. AI LIVE NOISE CLASSIFICATION & SOUND DIAGNOSTIC
${
  latestAiResult
    ? `
- **Primary AI Sound Guess:** ${latestAiResult.primarySound}
- **Category:** ${latestAiResult.category}
- **Match Confidence:** ${latestAiResult.confidence}%
- **Acoustic Description:** ${latestAiResult.description}
${latestAiResult.acousticCharacteristics ? `- **Acoustic Signature:** ${latestAiResult.acousticCharacteristics}` : ''}

### Psychoacoustic Characteristics
${
  latestAiResult.psychoacoustics
    ? `- **Sound Purity:** ${latestAiResult.psychoacoustics.soundPurity}
- **Estimated Perceived Loudness:** ${latestAiResult.psychoacoustics.perceivedLoudnessLufs} LUFS
- **Sharpness Score:** ${latestAiResult.psychoacoustics.sharpnessScore}%
- **Brightness Score:** ${latestAiResult.psychoacoustics.brightnessScore}%
- **Warmth Score:** ${latestAiResult.psychoacoustics.warmthScore}%
- **Harshness Score:** ${latestAiResult.psychoacoustics.harshnessScore}%`
    : 'N/A'
}

### Recommended Acoustic Fixes & Room Treatment
${
  latestAiResult.recommendedFixes
    ? `- **EQ Filter Action:** ${latestAiResult.recommendedFixes.eqAction}
- **Room Treatment Advice:** ${latestAiResult.recommendedFixes.roomTreatment}
- **Hardware / Noise Gate:** ${latestAiResult.recommendedFixes.hardwareFix}`
    : 'N/A'
}
`
    : '*No AI Sound Detection run during this session. Enable mic and click "Guess Live Noise Now".*'
}

---
*Report generated automatically by Professional Audio Analysis Suite.*
`.trim();
  };

  const reportText = buildReportMarkdown();

  // Prompt formatted specifically for Google Gemini consultation
  const buildGeminiPrompt = () => {
    return `Please analyze this Acoustic Sound Audit Report generated by my audio analyzer suite.

TASKS:
1. Provide a professional acoustic evaluation of the dominant frequency (${metrics.peakFrequencyFormatted || `${metrics.peakFrequencyHz} Hz`}), RMS levels, and noise floor (${profile.noiseFloorDb} dBFS).
2. Interpret the room Noise Criteria (${profile.noiseCriteriaRating}), SNR (+${profile.snrDb} dB), and impulsive transient count (${profile.transientCount} events).
3. Diagnose potential acoustic problems (e.g. room resonances, HVAC hum, flutter echoes, microphone gain staging issues, or background noise leaks).
4. Give concrete, actionable recommendations for room acoustic treatment, microphone positioning, and corrective EQ filters.

--- ACOUSTIC SOUND AUDIT REPORT ---
${reportText}`;
  };

  // Ask Gemini Handler: Copies prompt and opens Gemini in new tab
  const handleAskGemini = () => {
    const prompt = buildGeminiPrompt();
    navigator.clipboard.writeText(prompt);
    setGeminiState('copied');
    
    // Open Gemini in a new window/tab
    window.open('https://gemini.google.com', '_blank', 'noopener,noreferrer');
    
    setTimeout(() => {
      setGeminiState('idle');
    }, 4000);
  };

  // Download Markdown file
  const downloadMarkdown = () => {
    const blob = new Blob([reportText], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `Acoustic_Sound_Audit_${Date.now()}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Download JSON file
  const downloadJson = () => {
    const data = {
      reportType: 'ACOUSTIC_SOUND_AUDIT',
      timestamp,
      metrics,
      profile,
      aiNoiseResult: latestAiResult,
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `Acoustic_Sound_Audit_${Date.now()}.json`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Copy to clipboard
  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-md flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-3xl w-full shadow-2xl flex flex-col max-h-[85vh] overflow-hidden">
        {/* Header */}
        <div className="p-5 border-b border-slate-800 flex items-center justify-between bg-slate-950/80">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white tracking-wide">
                Export Acoustic Sound Audit Report
              </h3>
              <p className="text-xs text-slate-400">
                Professional diagnostic snapshot, spectral metrics, transient log & AI acoustic consultation
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            id="btn-close-report-modal"
            className="p-2 rounded-xl bg-slate-900 border border-slate-800 text-slate-400 hover:text-white hover:border-slate-700 cursor-pointer transition-all"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Gemini Direct Banner */}
        <div className="bg-gradient-to-r from-blue-950/40 via-indigo-950/40 to-purple-950/40 border-b border-indigo-500/20 px-5 py-3 flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-2 text-xs">
            <Sparkles className="w-4 h-4 text-indigo-400 shrink-0 animate-pulse" />
            <span className="text-slate-300">
              Discuss this report with <strong className="text-white">Google Gemini</strong> for expert acoustic analysis & treatment advice.
            </span>
          </div>
          <button
            onClick={handleAskGemini}
            id="btn-ask-gemini-top"
            className="px-3.5 py-1.5 rounded-xl text-xs font-bold bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 hover:from-blue-500 hover:via-indigo-500 hover:to-purple-500 text-white flex items-center gap-1.5 cursor-pointer transition-all shadow-md shadow-indigo-600/20"
          >
            {geminiState === 'copied' ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-300" />
                <span>Prompt Copied! Opening Gemini...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-3.5 h-3.5 text-indigo-200" />
                <span>Ask Gemini</span>
                <ExternalLink className="w-3 h-3 text-indigo-200 opacity-80" />
              </>
            )}
          </button>
        </div>

        {/* Report Preview */}
        <div className="p-5 overflow-y-auto flex-1 bg-slate-950/90 font-mono text-[11px] text-slate-300 whitespace-pre-wrap leading-relaxed border-b border-slate-800">
          {reportText}
        </div>

        {/* Action Buttons */}
        <div className="p-4 bg-slate-950 flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              id="btn-copy-report"
              className="px-3.5 py-2 rounded-xl text-xs font-semibold bg-slate-900 border border-slate-800 hover:border-slate-700 text-slate-200 flex items-center gap-2 cursor-pointer transition-all"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4 text-slate-400" />}
              {copied ? 'Copied Text!' : 'Copy Report'}
            </button>

            <button
              onClick={handleAskGemini}
              id="btn-ask-gemini-bottom"
              className="px-4 py-2 rounded-xl text-xs font-bold bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 hover:from-blue-500 hover:via-indigo-500 hover:to-purple-500 text-white flex items-center gap-2 cursor-pointer transition-all shadow-lg shadow-indigo-500/20"
            >
              {geminiState === 'copied' ? (
                <>
                  <Check className="w-4 h-4 text-emerald-300" />
                  <span>Copied! Opening Gemini...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-indigo-200" />
                  <span>Ask Gemini (gemini.google.com)</span>
                  <ExternalLink className="w-3.5 h-3.5 text-indigo-200 opacity-80" />
                </>
              )}
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={downloadJson}
              id="btn-download-report-json"
              className="px-3.5 py-2 rounded-xl text-xs font-semibold bg-slate-900 border border-slate-800 hover:border-slate-700 text-cyan-300 flex items-center gap-2 cursor-pointer transition-all"
            >
              <FileCode className="w-4 h-4 text-cyan-400" />
              JSON
            </button>

            <button
              onClick={downloadMarkdown}
              id="btn-download-report-md"
              className="px-4 py-2 rounded-xl text-xs font-bold bg-gradient-to-r from-emerald-500 to-cyan-600 hover:from-emerald-400 hover:to-cyan-500 text-slate-950 flex items-center gap-2 cursor-pointer transition-all shadow-lg shadow-emerald-500/20"
            >
              <Download className="w-4 h-4 text-slate-950" />
              Download Markdown (.md)
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
